import type { AdminUser } from '@/types/admin';

export const adminUsers: AdminUser[] = [
  {
    name: '겜돌이',
    handle: 'gamer01',
    id: 'usr_01',
    initial: '겜',
    avatarColor: '#315ef5',
    status: '활성',
    reports: 7,
    confirmedViolations: 2,
    sanction: '없음',
    registeredAt: '2025.03.14',
    role: '멘토',
  },
  {
    name: '미드킹',
    handle: 'midking',
    id: 'usr_02',
    initial: '미',
    avatarColor: '#0ea5a0',
    status: '정지',
    reports: 12,
    confirmedViolations: 4,
    sanction: '7일 정지',
    registeredAt: '2024.11.02',
  },
  {
    name: '서폿장인',
    handle: 'support22',
    id: 'usr_03',
    initial: '서',
    avatarColor: '#d97706',
    status: '활성',
    reports: 1,
    confirmedViolations: 0,
    sanction: '없음',
    registeredAt: '2025.06.21',
  },
  {
    name: '이벤트당첨',
    handle: 'spammer_x',
    id: 'usr_04',
    initial: '이',
    avatarColor: '#7c3aed',
    status: '정지',
    reports: 24,
    confirmedViolations: 10,
    sanction: '30일 정지',
    registeredAt: '2026.07.01',
  },
  {
    name: '페이커입니다',
    handle: 'faker_fake',
    id: 'usr_05',
    initial: '페',
    avatarColor: '#db2777',
    status: '활성',
    reports: 6,
    confirmedViolations: 1,
    sanction: '경고',
    registeredAt: '2026.05.18',
  },
  {
    name: '정글차이',
    handle: 'toxic99',
    id: 'usr_06',
    initial: '정',
    avatarColor: '#0891b2',
    status: '활성',
    reports: 4,
    confirmedViolations: 1,
    sanction: '없음',
    registeredAt: '2025.01.09',
  },
  {
    name: '매너겐지',
    handle: 'cleanplayer',
    id: 'usr_07',
    initial: '매',
    avatarColor: '#16a34a',
    status: '활성',
    reports: 0,
    confirmedViolations: 0,
    sanction: '없음',
    registeredAt: '2025.09.30',
  },
  {
    name: '관리자 이서연',
    handle: 'admin02',
    id: 'adm_02',
    initial: '관',
    avatarColor: '#315ef5',
    status: '활성',
    reports: 0,
    confirmedViolations: 0,
    sanction: '없음',
    registeredAt: '2024.02.01',
    role: '관리자',
  },
];

export function findAdminUser(handle: string) {
  return adminUsers.find((user) => user.handle === handle);
}
