import type { AdminReport, AdminReportUser } from '@/types/admin';

const reporterProfiles: Record<string, AdminReportUser> = {
  '@support22': {
    name: '서폿장인',
    handle: '@support22',
    initial: '서',
    joinedAt: '2025.06.21',
    reportsReceived: 1,
  },
  '@cleanplayer': {
    name: '클린플레이어',
    handle: '@cleanplayer',
    initial: '클',
    joinedAt: '2025.09.03',
    reportsReceived: 0,
  },
  '@gamer01': {
    name: '게이머01',
    handle: '@gamer01',
    initial: '게',
    joinedAt: '2024.11.18',
    reportsReceived: 2,
  },
  '@midking': {
    name: '미드킹',
    handle: '@midking',
    initial: '미',
    joinedAt: '2025.03.12',
    reportsReceived: 1,
  },
};

const defaultTargetUser: AdminReportUser = {
  name: '정글차이',
  handle: '@toxic99',
  initial: '정',
  joinedAt: '2025.01.09',
  reportsReceived: 4,
  activeSanction: '제재 없음',
};

export const reports: AdminReport[] = [
  {
    id: 'RPT-1024',
    targetType: '게시글',
    target: '게임도 못하면서 왜 큐를 돌려…',
    reason: '욕설·비하·혐오',
    status: '접수',
    reporter: '@support22',
    administrator: '미배정',
    receivedAt: '2026.07.23 20:10',
    description: '상대방이 게시글과 댓글을 통해 반복적으로 욕설을 사용했습니다.',
    content: '게임도 못하면서 왜 큐를 돌려 ㅋㅋ 그냥 접어라 진짜. 던지지 좀 마라.',
    reporterUser: reporterProfiles['@support22'],
    targetUser: defaultTargetUser,
  },
  {
    id: 'RPT-1023',
    targetType: '댓글',
    target: '무료 스킨 이벤트 링크 → bit.ly/…',
    reason: '도배·시스템 악용',
    status: '검토 중',
    reporter: '@cleanplayer',
    administrator: '관리자 김민수',
    receivedAt: '2026.07.23 19:42',
    description: '동일한 외부 링크를 여러 게시글의 댓글에 반복적으로 등록했습니다.',
    content: '무료 스킨 이벤트 진행 중! 자세한 내용은 bit.ly/gamerin-event 에서 확인하세요.',
    reporterUser: reporterProfiles['@cleanplayer'],
    targetUser: { ...defaultTargetUser, name: '이벤트알림', handle: '@event_push', initial: '이' },
  },
  {
    id: 'RPT-1022',
    targetType: '사용자',
    target: '@faker_fake 프로게이머 사칭',
    reason: '기타',
    status: '처리 완료',
    reporter: '@gamer01',
    administrator: '관리자 김민수',
    receivedAt: '2026.07.23 15:20',
    description: '프로게이머를 사칭하는 닉네임과 프로필 정보를 사용하고 있습니다.',
    content: '프로게이머 공식 계정입니다. 개인 코칭 문의는 DM으로 보내주세요.',
    reporterUser: reporterProfiles['@gamer01'],
    targetUser: { ...defaultTargetUser, name: '페이커', handle: '@faker_fake', initial: '페' },
  },
  {
    id: 'RPT-1021',
    targetType: '메시지',
    target: 'DM으로 계정 거래 유도',
    reason: '사기·거래 피해',
    status: '반려',
    reporter: '@midking',
    administrator: '관리자 이서연',
    receivedAt: '2026.07.23 12:05',
    description: '개인 메시지로 게임 계정 거래를 반복해서 권유했습니다.',
    content: '티어 높은 계정 저렴하게 판매합니다. 관심 있으면 개인 연락 주세요.',
    reporterUser: reporterProfiles['@midking'],
    targetUser: { ...defaultTargetUser, name: '계정거래', handle: '@account_shop', initial: '계' },
  },
  {
    id: 'RPT-1020',
    targetType: '게시글',
    target: '특정 유저 저격 및 신상 언급',
    reason: '기타',
    status: '접수',
    reporter: '@gamer01',
    administrator: '미배정',
    receivedAt: '2026.07.23 09:31',
    description: '특정 사용자를 지목하고 개인정보로 추정되는 내용을 게시했습니다.',
    content: '이 유저 조심하세요. 실제 이름이랑 사는 곳도 알고 있습니다.',
    reporterUser: reporterProfiles['@gamer01'],
    targetUser: { ...defaultTargetUser, name: '탑신병자', handle: '@top_only', initial: '탑' },
  },
  {
    id: 'RPT-1019',
    targetType: '댓글',
    target: '반복적인 욕설 댓글',
    reason: '욕설·비하·혐오',
    status: '처리 완료',
    reporter: '@support22',
    administrator: '관리자 김민수',
    receivedAt: '2026.07.22 22:14',
    description: '여러 댓글에서 동일 사용자를 향한 욕설과 비방을 반복했습니다.',
    content: '실력도 없으면서 아는 척하지 마라. 매번 팀 탓만 하네.',
    reporterUser: reporterProfiles['@support22'],
    targetUser: defaultTargetUser,
  },
  {
    id: 'RPT-1018',
    targetType: '게시글',
    target: '대리 랭크 광고 및 외부 연락 유도',
    reason: '광고·홍보',
    status: '검토 중',
    reporter: '@cleanplayer',
    administrator: '관리자 이서연',
    receivedAt: '2026.07.22 18:30',
    description: '대리 게임을 홍보하며 외부 메신저 연락을 유도했습니다.',
    content: '랭크 대리 빠르게 진행합니다. 오픈채팅으로 문의 주세요.',
    reporterUser: reporterProfiles['@cleanplayer'],
    targetUser: { ...defaultTargetUser, name: '랭크도우미', handle: '@rank_helper', initial: '랭' },
  },
  {
    id: 'RPT-1017',
    targetType: '댓글',
    target: '선정적인 이미지 링크 공유',
    reason: '음란·성적 콘텐츠',
    status: '접수',
    reporter: '@gamer01',
    administrator: '미배정',
    receivedAt: '2026.07.22 16:48',
    description: '게임과 무관한 선정적인 외부 이미지 링크가 포함되어 있습니다.',
    content: '이 링크 눌러보면 더 재미있는 사진 많음.',
    reporterUser: reporterProfiles['@gamer01'],
    targetUser: { ...defaultTargetUser, name: '링크공유', handle: '@random_link', initial: '링' },
  },
  {
    id: 'RPT-1016',
    targetType: '메시지',
    target: '아이템 선입금 사기 의심 메시지',
    reason: '사기·거래 피해',
    status: '처리 완료',
    reporter: '@midking',
    administrator: '관리자 김민수',
    receivedAt: '2026.07.22 13:15',
    description: '아이템 판매를 빌미로 선입금을 요구한 뒤 답변하지 않았습니다.',
    content: '먼저 입금하면 아이템 바로 보내드릴게요. 지금만 할인합니다.',
    reporterUser: reporterProfiles['@midking'],
    targetUser: { ...defaultTargetUser, name: '아이템상점', handle: '@item_shop', initial: '아' },
  },
  {
    id: 'RPT-1015',
    targetType: '사용자',
    target: '@repeat_bot 반복 게시 사용자',
    reason: '도배·시스템 악용',
    status: '반려',
    reporter: '@support22',
    administrator: '관리자 이서연',
    receivedAt: '2026.07.22 10:02',
    description: '짧은 시간 동안 동일한 내용의 게시글을 반복 등록했습니다.',
    content: '같이 게임하실 분 구합니다.',
    reporterUser: reporterProfiles['@support22'],
    targetUser: { ...defaultTargetUser, name: '반복봇', handle: '@repeat_bot', initial: '반' },
  },
];

export function getReportById(reportId: string) {
  return reports.find((report) => report.id.toLowerCase() === reportId.toLowerCase());
}
